COMMUNICATION_TIMEOUT = 1800  # 1800 = 30 minutes
DRY_RUN = True


# Inverter Read registers
# Register Data Locations
WORK_MODE_REGISTER = 0x008B
MANUAL_MODE_REGISTER = 0x008C

WORK_MODE_WRITE_REGISTER = 31
MANUAL_MODE_WRITE_REGISTER = 32

REGISTER_BLOCK_START = 0
REGISTER_BLOCK_SIZE = 80

INVERTER_POWER = 2

PV1_POWER = 10
PV2_POWER = 11

BATTERY_POWER = 22
BATTERY_SOC = 28

GRID_LSB = 70
GRID_MSB = 71

#FORCED_DISCHARE = 140

#Scheduler Requested Operation
SCHEDULER_MODE_MANUAL_CHARGE = "MANUAL_CHARGE"
SCHEDULER_MODE_MANUAL_DISCHARGE = "MANUAL_DISCHARGE"
SCHEDULER_MODE_SELF_USE = "SELF_USE"
SCHEDULER_MODE_PEAK_SHAVING = "PEAK_SHAVING"
SCHEDULER_MODE_FEED_IN = "FEED_IN"
SCHEDULER_MODE_BACKUP = "BACKUP"