COMMUNICATION_TIMEOUT = 1800  # 1800 = 30 minutes
DRY_RUN = True


# Inverter Read registers
# Register Data Locations
WORK_MODE_REGISTER = 0x008B
MANUAL_MODE_REGISTER = 0x008C

REGISTER_BLOCK_START = 0
REGISTER_BLOCK_SIZE = 80

INVERTER_POWER = 2

PV1_POWER = 10
PV2_POWER = 11

BATTERY_POWER = 22
BATTERY_SOC = 28

GRID_LSB = 70
GRID_MSB = 71

#FORCED_DISCHARE = 140

# Register Values
WORK_MODE_SELF_USE = 0
WORK_MODE_FEED_IN = 1
WORK_MODE_BACKUP = 2
WORK_MODE_MANUAL = 3
WORK_MODE_PEAK_SHAVING = 4
WORK_MODE_TOU = 5

MANUAL_MODE_IDLE = 0
MANUAL_MODE_FORCE_CHARGE = 1
MANUAL_MODE_FORCE_DISCHARGE = 2

MODE_SELF_USE=0
MODE_FEED_IN = 1
MODE_BACKUP = 2
MODE_MANUAL = 3

#Scheduler Requested Operation
SCHEDULER_MODE_MANUAL_CHARGE = "MANUAL_CHARGE"
SCHEDULER_MODE_MANUAL_DISCHARGE = "MANUAL_DISCHARGE"
SCHEDULER_MODE_SELF_USE = "SELF_USE"
SCHEDULER_MODE_PEAK_SHAVING = "PEAK_SHAVING"
SCHEDULER_MODE_FEED_IN = "FEED_IN"
SCHEDULER_MODE_BACKUP = "BACKUP"