INVERTER_POWER = 2

PV1_POWER = 10
PV2_POWER = 11

BATTERY_POWER = 22
BATTERY_SOC = 28

GRID_LSB = 70
GRID_MSB = 71

FORCED_DISCHARE = 140


# Inverter Read registers

WORK_MODE_REGISTER = 0x008B
MANUAL_MODE_REGISTER = 0x008C

WORK_MODE_SELF_USE = 0
WORK_MODE_FEED_IN = 1
WORK_MODE_BACKUP = 2
WORK_MODE_MANUAL = 3
WORK_MODE_PEAK = 4
WORK_MODE_TOU = 5

MANUAL_STOP = 0
MANUAL_FORCE_CHARGE = 1
MANUAL_FORCE_DISCHARGE = 2